/**
 * Classification of events in the Event Fabric.
 * Determines how events are processed, routed, and retained.
 */
export const EventClassification = {
  /** Facts about business operations (e.g., OrderCreated, PaymentReceived) */
  DOMAIN: 'DOMAIN',
  /** Insights, predictions, anomalies generated by Business Intelligence */
  INTELLIGENCE: 'INTELLIGENCE',
  /** Decisions made by the Decision Engine */
  DECISION: 'DECISION',
  /** Actions taken as a result of decisions (e.g., NotificationSent, WorkflowStarted) */
  EXECUTION: 'EXECUTION',
  /** Audit trail events (immutable log of system activities) */
  AUDIT: 'AUDIT',
  /** System-level events (e.g., NodeStarted, ConfigurationChanged) */
  SYSTEM: 'SYSTEM',
  /** Events from external systems or third-party integrations */
  INTEGRATION: 'INTEGRATION'
} as const;

export type EventClassification = typeof EventClassification[keyof typeof EventClassification];