import { createFileRoute } from "@tanstack/react-router";
import { ResourcePage } from "@/components/landing/ResourcePage";
import { Code2, Webhook, KeyRound, Cable, GitBranch, Terminal } from "lucide-react";

export const Route = createFileRoute("/resources/api")({
  head: () => ({
    meta: [
      { title: "API Documentation — Sentinel Fort Group" },
      { name: "description", content: "REST APIs, webhooks, event schemas and SDKs to embed and extend Sentinel across your stack." },
      { property: "og:title", content: "Sentinel API Documentation" },
      { property: "og:description", content: "REST APIs, webhooks and SDKs for the Sentinel platform." },
    ],
  }),
  component: ApiPage,
});

function ApiPage() {
  return (
    <ResourcePage
      eyebrow="Resources · Developers"
      title={<>Build on the <span className="text-primary">Sentinel platform</span>.</>}
      lead="REST APIs, webhooks, event schemas and SDKs to embed Sentinel into your website, data warehouse and internal tools."
      highlights={["REST + Webhooks", "Event bus", "OAuth 2.0", "TypeScript SDK"]}
      sections={[
        { icon: Code2, title: "REST API", description: "Typed endpoints for leads, properties, bookings, collections and users." },
        { icon: Webhook, title: "Webhooks", description: "Real-time notifications on state changes with signed payloads and replay." },
        { icon: KeyRound, title: "Authentication", description: "OAuth 2.0 with PKCE, scoped tokens and workspace-aware permissions." },
        { icon: Cable, title: "Integrations", description: "Prebuilt connectors for payment gateways, WhatsApp, Meta, Google and Slack." },
        { icon: GitBranch, title: "Event Schemas", description: "Versioned event contracts for downstream consumers and data pipelines." },
        { icon: Terminal, title: "SDKs", description: "TypeScript SDK with autogenerated types; Python and Go coming soon." },
      ]}
      cta={{ label: "Talk to Developer Relations", to: "/contact" }}
      related={[
        { label: "Documentation", to: "/resources/documentation" },
        { label: "Release Notes", to: "/resources/release-notes" },
        { label: "System Status", to: "/resources/status" },
      ]}
    />
  );
}