/**
 * Customer Intelligence Service
 *
 * Processes live customer records from the repository and returns
 * a meaningful CustomerIntelligence object with real aggregations,
 * groupings, engagement analysis, and risk identification.
 */

import type { ICustomerRepository } from "./repository";
import type {
  CustomerIntelligence,
  CustomerLevel,
  CustomerMovement,
  CustomerSummary,
  CustomerGrouping,
  EngagementBucket,
} from "./types";

// ─── Engagement bucket boundaries (in days) ───
const ENGAGEMENT_BUCKETS = [
  { label: "0-7 days", maxDays: 7 },
  { label: "8-30 days", maxDays: 30 },
  { label: "31-60 days", maxDays: 60 },
  { label: "61-90 days", maxDays: 90 },
  { label: "Over 90 days", maxDays: Infinity },
];

// ─── At-risk threshold: customers with no activity for this many days ───
const AT_RISK_THRESHOLD_DAYS = 60;

// ─── High-value threshold: customers with total value above this multiple of avg ───
const HIGH_VALUE_MULTIPLE = 2.0;

export class CustomerIntelligenceService {
  constructor(private repository: ICustomerRepository) {}

  /**
   * Fetches raw customer levels from the repository.
   */
  async getLevels(workspaceId: string): Promise<CustomerLevel[]> {
    return this.repository.getLevels(workspaceId);
  }

  /**
   * Fetches customer movements. Since the repository interface is per-contact,
   * we aggregate across all levels in the workspace.
   * Returns an empty array when no movements table exists (truthful fallback).
   */
  async getMovements(workspaceId: string): Promise<CustomerMovement[]> {
    const levels = await this.repository.getLevels(workspaceId);
    const movements: CustomerMovement[] = [];
    for (const level of levels) {
      try {
        const levelMovements = await this.repository.getMovements(level.contactId);
        movements.push(...levelMovements);
      } catch {
        // Movements table may not exist; truthful empty fallback
      }
    }
    return movements;
  }

  /**
   * Calculates a real summary from live customer levels.
   */
  async getSummary(workspaceId: string): Promise<Record<string, unknown>> {
    const levels = await this.getLevels(workspaceId);
    return this.calculateSummary(levels) as unknown as Record<string, unknown>;
  }

  /**
   * Returns the full intelligence context: levels, movements, summary,
   * groupings, engagement buckets, at-risk, and high-value customers.
   */
  async getContext(workspaceId: string): Promise<CustomerIntelligence> {
    const [levels, movements] = await Promise.all([
      this.getLevels(workspaceId),
      this.getMovements(workspaceId),
    ]);

    const customerSummary = this.calculateSummary(levels);
    const groupings = this.calculateGroupings(levels);
    const engagementBuckets = this.calculateEngagementBuckets(levels);
    const atRiskCustomers = this.identifyAtRiskCustomers(levels);
    const highValueCustomers = this.identifyHighValueCustomers(levels);

    return {
      levels,
      movements,
      summary: customerSummary,
      customerSummary,
      groupings,
      engagementBuckets,
      atRiskCustomers,
      highValueCustomers,
      generatedAt: new Date().toISOString(),
    };
  }

  /**
   * Generates recommendations from the intelligence context.
   * Delegates to the decision engine in the full cycle; this method
   * provides a direct BI-layer view for testing.
   */
  async getRecommendations(
    workspaceId: string,
  ): Promise<Record<string, unknown>[]> {
    const context = await this.getContext(workspaceId);
    // Recommendations are generated by the decision engine in the full cycle.
    // This method returns the raw intelligence for backward compatibility.
    return [
      {
        workspaceId,
        generatedAt: context.generatedAt,
        summary: context.customerSummary,
      },
    ];
  }

  // ─── Private calculation helpers ──────────────────────────────────

  private calculateSummary(levels: CustomerLevel[]): CustomerSummary {
    const total = levels.length;
    let active = 0;
    let newCount = 0;
    let inactive = 0;
    let customer = 0;
    let partner = 0;
    let vendor = 0;
    let referral = 0;
    let archived = 0;
    let totalValue = 0;
    let totalEngagementScore = 0;
    let engagementCount = 0;
    let doNotContact = 0;

    for (const level of levels) {
      const status = (level.status ?? "NEW").toUpperCase();
      const value = level.totalValueInr ?? 0;

      totalValue += value;

      if (level.engagementScore !== undefined) {
        totalEngagementScore += level.engagementScore;
        engagementCount++;
      }

      if (level.doNotContact) doNotContact++;

      switch (status) {
        case "ACTIVE":
          active++;
          break;
        case "NEW":
          newCount++;
          break;
        case "INACTIVE":
          inactive++;
          break;
        case "CUSTOMER":
          customer++;
          break;
        case "PARTNER":
          partner++;
          break;
        case "VENDOR":
          vendor++;
          break;
        case "REFERRAL":
          referral++;
          break;
        case "ARCHIVED":
          archived++;
          break;
        default:
          // Default to new
          newCount++;
      }
    }

    const activePct = total > 0 ? (active / total) * 100 : 0;
    const customerPct = total > 0 ? (customer / total) * 100 : 0;
    const inactivePct = total > 0 ? (inactive / total) * 100 : 0;
    const doNotContactPct = total > 0 ? (doNotContact / total) * 100 : 0;
    const avgEngagementScore = engagementCount > 0 ? totalEngagementScore / engagementCount : 0;

    return {
      total,
      active,
      new: newCount,
      inactive,
      customer,
      partner,
      vendor,
      referral,
      archived,
      totalValueInr: totalValue,
      avgEngagementScore: Math.round(avgEngagementScore * 100) / 100,
      activePct: Math.round(activePct * 100) / 100,
      customerPct: Math.round(customerPct * 100) / 100,
      inactivePct: Math.round(inactivePct * 100) / 100,
      doNotContactPct: Math.round(doNotContactPct * 100) / 100,
    };
  }

  private calculateGroupings(levels: CustomerLevel[]): {
    byCity: CustomerGrouping[];
    byStatus: CustomerGrouping[];
    byLeadSource: CustomerGrouping[];
    byCompany: CustomerGrouping[];
  } {
    return {
      byCity: this.groupBy(levels, (l) => l.city ?? "Unknown"),
      byStatus: this.groupBy(levels, (l) => (l.status ?? "NEW").toUpperCase()),
      byLeadSource: this.groupBy(levels, (l) => l.leadSource ?? "Unknown"),
      byCompany: this.groupBy(levels, (l) => l.company ?? "Unknown"),
    };
  }

  private groupBy(
    levels: CustomerLevel[],
    keyFn: (level: CustomerLevel) => string,
  ): CustomerGrouping[] {
    const map = new Map<string, CustomerGrouping>();

    for (const level of levels) {
      const key = keyFn(level);
      const existing = map.get(key) ?? {
        name: key,
        total: 0,
        active: 0,
        new: 0,
        inactive: 0,
        customer: 0,
        value: 0,
        avgEngagementScore: 0,
      };

      existing.total++;
      existing.value += level.totalValueInr ?? 0;

      if (level.engagementScore !== undefined) {
        // Running average
        existing.avgEngagementScore =
          (existing.avgEngagementScore * (existing.total - 1) + level.engagementScore) /
          existing.total;
      }

      const status = (level.status ?? "NEW").toUpperCase();
      if (status === "ACTIVE") existing.active++;
      else if (status === "NEW") existing.new++;
      else if (status === "INACTIVE") existing.inactive++;
      else if (status === "CUSTOMER") existing.customer++;

      map.set(key, existing);
    }

    return Array.from(map.values());
  }

  private calculateEngagementBuckets(levels: CustomerLevel[]): EngagementBucket[] {
    const now = Date.now();
    const buckets: EngagementBucket[] = ENGAGEMENT_BUCKETS.map((b) => ({
      bucket: b.label,
      count: 0,
      avgEngagementScore: 0,
    }));

    for (const level of levels) {
      const lastActivity = level.lastActivityAt
        ? new Date(level.lastActivityAt).getTime()
        : level.createdAt
        ? new Date(level.createdAt).getTime()
        : now;
      const ageDays = Math.floor((now - lastActivity) / 86_400_000);

      for (let i = 0; i < ENGAGEMENT_BUCKETS.length; i++) {
        const prevMax = i > 0 ? ENGAGEMENT_BUCKETS[i - 1].maxDays : 0;
        if (ageDays > prevMax && ageDays <= ENGAGEMENT_BUCKETS[i].maxDays) {
          buckets[i].count++;
          if (level.engagementScore !== undefined) {
            // Running average
            buckets[i].avgEngagementScore =
              (buckets[i].avgEngagementScore * (buckets[i].count - 1) + level.engagementScore) /
              buckets[i].count;
          }
          break;
        }
      }
    }

    return buckets;
  }

  private identifyAtRiskCustomers(levels: CustomerLevel[]): CustomerLevel[] {
    const now = Date.now();
    return levels.filter((level) => {
      const status = (level.status ?? "NEW").toUpperCase();
      // Only consider active/new/customer statuses as at-risk
      if (!["ACTIVE", "NEW", "CUSTOMER"].includes(status)) return false;
      if (level.doNotContact) return false;

      const lastActivity = level.lastActivityAt
        ? new Date(level.lastActivityAt).getTime()
        : level.createdAt
        ? new Date(level.createdAt).getTime()
        : now;
      const ageDays = Math.floor((now - lastActivity) / 86_400_000);
      return ageDays > AT_RISK_THRESHOLD_DAYS;
    });
  }

  private identifyHighValueCustomers(levels: CustomerLevel[]): CustomerLevel[] {
    const valuable = levels.filter(
      (l) => (l.totalValueInr ?? 0) > 0,
    );
    if (valuable.length === 0) return [];

    const avgValue =
      valuable.reduce((sum, l) => sum + (l.totalValueInr ?? 0), 0) / valuable.length;
    const threshold = avgValue * HIGH_VALUE_MULTIPLE;

    return valuable
      .filter((l) => (l.totalValueInr ?? 0) > threshold)
      .sort((a, b) => (b.totalValueInr ?? 0) - (a.totalValueInr ?? 0));
  }
}