/**
 * Inventory Intelligence Service
 *
 * Processes live inventory records from the repository and returns
 * a meaningful InventoryIntelligence object with real aggregations,
 * groupings, ageing analysis, and risk identification.
 */

import type { IInventoryRepository } from "./repository";
import type {
  InventoryIntelligence,
  InventoryLevel,
  InventoryMovement,
  InventorySummary,
  InventoryGrouping,
  AgeingBucket,
} from "./types";

// ── Ageing bucket boundaries (in days) ──
const AGEING_BUCKETS = [
  { label: "0-30 days", maxDays: 30 },
  { label: "31-60 days", maxDays: 60 },
  { label: "61-90 days", maxDays: 90 },
  { label: "91-120 days", maxDays: 120 },
  { label: "Over 120 days", maxDays: Infinity },
];

// ── Slow-moving threshold: available inventory older than this is "slow" ──
const SLOW_MOVING_THRESHOLD_DAYS = 90;

// ── High-value threshold: available inventory priced above this multiple of avg ──
const HIGH_VALUE_MULTIPLE = 1.5;

export class InventoryIntelligenceService {
  constructor(private repository: IInventoryRepository) {}

  /**
   * Fetches raw inventory levels from the repository.
   */
  async getLevels(workspaceId: string): Promise<InventoryLevel[]> {
    return this.repository.getLevels(workspaceId);
  }

  /**
   * Fetches inventory movements. Since the repository interface is per-asset,
   * we aggregate across all levels in the workspace.
   * Returns an empty array when no movements table exists (truthful fallback).
   */
  async getMovements(workspaceId: string): Promise<InventoryMovement[]> {
    const levels = await this.repository.getLevels(workspaceId);
    const movements: InventoryMovement[] = [];
    for (const level of levels) {
      try {
        const levelMovements = await this.repository.getMovements(level.assetId);
        movements.push(...levelMovements);
      } catch {
        // Movements table may not exist; truthful empty fallback
      }
    }
    return movements;
  }

  /**
   * Calculates a real summary from live inventory levels.
   */
  async getSummary(workspaceId: string): Promise<Record<string, unknown>> {
    const levels = await this.getLevels(workspaceId);
    return this.calculateSummary(levels) as unknown as Record<string, unknown>;
  }

  /**
   * Returns the full intelligence context: levels, movements, summary,
   * groupings, ageing buckets, slow-moving, and high-value unsold inventory.
   */
  async getContext(workspaceId: string): Promise<InventoryIntelligence> {
    const [levels, movements] = await Promise.all([
      this.getLevels(workspaceId),
      this.getMovements(workspaceId),
    ]);

    const inventorySummary = this.calculateSummary(levels);
    const groupings = this.calculateGroupings(levels);
    const ageingBuckets = this.calculateAgeingBuckets(levels);
    const slowMoving = this.identifySlowMoving(levels);
    const highValueUnsold = this.identifyHighValueUnsold(levels);

    return {
      levels,
      movements,
      summary: inventorySummary,
      inventorySummary,
      groupings,
      ageingBuckets,
      slowMoving,
      highValueUnsold,
      generatedAt: new Date().toISOString(),
    };
  }

  /**
   * Generates recommendations from the intelligence context.
   * Delegates to the decision engine in the full cycle; this method
   * provides a direct BI-layer view for testing.
   */
  async getRecommendations(
    workspaceId: string,
  ): Promise<Record<string, unknown>[]> {
    const context = await this.getContext(workspaceId);
    // Recommendations are generated by the decision engine in the full cycle.
    // This method returns the raw intelligence for backward compatibility.
    return [
      {
        workspaceId,
        generatedAt: context.generatedAt,
        summary: context.inventorySummary,
      },
    ];
  }

  // ── Private calculation helpers ──────────────────────────────────

  private calculateSummary(levels: InventoryLevel[]): InventorySummary {
    const total = levels.length;
    let available = 0;
    let sold = 0;
    let reserved = 0;
    let blocked = 0;
    let totalValue = 0;
    let availableValue = 0;
    let soldValue = 0;

    for (const level of levels) {
      const status = (level.status ?? "available").toLowerCase();
      const value = level.priceInr ?? 0;

      totalValue += value;

      if (status === "sold") {
        sold++;
        soldValue += value;
      } else if (status === "reserved") {
        reserved++;
      } else if (status === "blocked" || status === "unavailable") {
        blocked++;
      } else {
        // Default: available
        available++;
        availableValue += value;
      }
    }

    const availabilityPct = total > 0 ? (available / total) * 100 : 0;
    const soldPct = total > 0 ? (sold / total) * 100 : 0;
    // Absorption = sold / (sold + available) — how much of sellable inventory has sold
    const sellable = sold + available;
    const absorptionPct = sellable > 0 ? (sold / sellable) * 100 : 0;
    const avgValue = total > 0 ? totalValue / total : 0;

    return {
      total,
      available,
      sold,
      reserved,
      blocked,
      availabilityPct: Math.round(availabilityPct * 100) / 100,
      soldPct: Math.round(soldPct * 100) / 100,
      absorptionPct: Math.round(absorptionPct * 100) / 100,
      avgValue: Math.round(avgValue),
      totalValue,
      availableValue,
      soldValue,
    };
  }

  private calculateGroupings(levels: InventoryLevel[]): {
    byCity: InventoryGrouping[];
    byStatus: InventoryGrouping[];
    byProject: InventoryGrouping[];
  } {
    return {
      byCity: this.groupBy(levels, (l) => l.city ?? "Unknown"),
      byStatus: this.groupBy(levels, (l) => (l.status ?? "available").toLowerCase()),
      byProject: this.groupBy(levels, (l) => l.developer ?? l.name ?? "Unknown"),
    };
  }

  private groupBy(
    levels: InventoryLevel[],
    keyFn: (level: InventoryLevel) => string,
  ): InventoryGrouping[] {
    const map = new Map<string, InventoryGrouping>();

    for (const level of levels) {
      const key = keyFn(level);
      const existing = map.get(key) ?? {
        name: key,
        total: 0,
        available: 0,
        sold: 0,
        reserved: 0,
        blocked: 0,
        value: 0,
      };

      existing.total++;
      existing.value += level.priceInr ?? 0;

      const status = (level.status ?? "available").toLowerCase();
      if (status === "sold") existing.sold++;
      else if (status === "reserved") existing.reserved++;
      else if (status === "blocked" || status === "unavailable") existing.blocked++;
      else existing.available++;

      map.set(key, existing);
    }

    return Array.from(map.values());
  }

  private calculateAgeingBuckets(levels: InventoryLevel[]): AgeingBucket[] {
    const now = Date.now();
    const buckets: AgeingBucket[] = AGEING_BUCKETS.map((b) => ({
      bucket: b.label,
      count: 0,
      value: 0,
    }));

    for (const level of levels) {
      const created = level.lastUpdated ? new Date(level.lastUpdated).getTime() : now;
      const ageDays = Math.floor((now - created) / 86_400_000);

      for (let i = 0; i < AGEING_BUCKETS.length; i++) {
        const prevMax = i > 0 ? AGEING_BUCKETS[i - 1].maxDays : 0;
        if (ageDays > prevMax && ageDays <= AGEING_BUCKETS[i].maxDays) {
          buckets[i].count++;
          buckets[i].value += level.priceInr ?? 0;
          break;
        }
      }
    }

    return buckets;
  }

  private identifySlowMoving(levels: InventoryLevel[]): InventoryLevel[] {
    const now = Date.now();
    return levels.filter((level) => {
      const status = (level.status ?? "available").toLowerCase();
      if (status !== "available") return false;
      const created = level.lastUpdated ? new Date(level.lastUpdated).getTime() : now;
      const ageDays = Math.floor((now - created) / 86_400_000);
      return ageDays > SLOW_MOVING_THRESHOLD_DAYS;
    });
  }

  private identifyHighValueUnsold(levels: InventoryLevel[]): InventoryLevel[] {
    const available = levels.filter(
      (l) => (l.status ?? "available").toLowerCase() === "available",
    );
    if (available.length === 0) return [];

    const avgPrice =
      available.reduce((sum, l) => sum + (l.priceInr ?? 0), 0) / available.length;
    const threshold = avgPrice * HIGH_VALUE_MULTIPLE;

    return available
      .filter((l) => (l.priceInr ?? 0) > threshold)
      .sort((a, b) => (b.priceInr ?? 0) - (a.priceInr ?? 0));
  }
}
