/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkflowsRouteImport } from './routes/app.workflows'
import { Route as AppVoiceRouteImport } from './routes/app.voice'
import { Route as AppRiskRouteImport } from './routes/app.risk'
import { Route as AppRecommendationsRouteImport } from './routes/app.recommendations'
import { Route as AppMarketplaceRouteImport } from './routes/app.marketplace'
import { Route as AppMarketRouteImport } from './routes/app.market'
import { Route as AppLeadsRouteImport } from './routes/app.leads'
import { Route as AppKieRouteImport } from './routes/app.kie'
import { Route as AppGraphRouteImport } from './routes/app.graph'
import { Route as AppFeedRouteImport } from './routes/app.feed'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppDealroomsRouteImport } from './routes/app.dealrooms'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppCopilotRouteImport } from './routes/app.copilot'
import { Route as AppCommandRouteImport } from './routes/app.command'
import { Route as AppBiRouteImport } from './routes/app.bi'
import { Route as AppSettingsBrandingRouteImport } from './routes/app.settings.branding'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkflowsRoute = AppWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppVoiceRoute = AppVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskRoute = AppRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => AppRoute,
} as any)
const AppRecommendationsRoute = AppRecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketplaceRoute = AppMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketRoute = AppMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppKieRoute = AppKieRouteImport.update({
  id: '/kie',
  path: '/kie',
  getParentRoute: () => AppRoute,
} as any)
const AppGraphRoute = AppGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedRoute = AppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDealroomsRoute = AppDealroomsRouteImport.update({
  id: '/dealrooms',
  path: '/dealrooms',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRoute,
} as any)
const AppCommandRoute = AppCommandRouteImport.update({
  id: '/command',
  path: '/command',
  getParentRoute: () => AppRoute,
} as any)
const AppBiRoute = AppBiRouteImport.update({
  id: '/bi',
  path: '/bi',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBrandingRoute = AppSettingsBrandingRouteImport.update({
  id: '/settings/branding',
  path: '/settings/branding',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bi': typeof AppBiRoute
  '/app/command': typeof AppCommandRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dealrooms': typeof AppDealroomsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/feed': typeof AppFeedRoute
  '/app/graph': typeof AppGraphRoute
  '/app/kie': typeof AppKieRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/market': typeof AppMarketRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/app/': typeof AppIndexRoute
  '/app/settings/branding': typeof AppSettingsBrandingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/bi': typeof AppBiRoute
  '/app/command': typeof AppCommandRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dealrooms': typeof AppDealroomsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/feed': typeof AppFeedRoute
  '/app/graph': typeof AppGraphRoute
  '/app/kie': typeof AppKieRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/market': typeof AppMarketRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/app': typeof AppIndexRoute
  '/app/settings/branding': typeof AppSettingsBrandingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/bi': typeof AppBiRoute
  '/app/command': typeof AppCommandRoute
  '/app/copilot': typeof AppCopilotRoute
  '/app/crm': typeof AppCrmRoute
  '/app/dealrooms': typeof AppDealroomsRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/feed': typeof AppFeedRoute
  '/app/graph': typeof AppGraphRoute
  '/app/kie': typeof AppKieRoute
  '/app/leads': typeof AppLeadsRoute
  '/app/market': typeof AppMarketRoute
  '/app/marketplace': typeof AppMarketplaceRoute
  '/app/recommendations': typeof AppRecommendationsRoute
  '/app/risk': typeof AppRiskRoute
  '/app/voice': typeof AppVoiceRoute
  '/app/workflows': typeof AppWorkflowsRoute
  '/app/': typeof AppIndexRoute
  '/app/settings/branding': typeof AppSettingsBrandingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/bi'
    | '/app/command'
    | '/app/copilot'
    | '/app/crm'
    | '/app/dealrooms'
    | '/app/documents'
    | '/app/feed'
    | '/app/graph'
    | '/app/kie'
    | '/app/leads'
    | '/app/market'
    | '/app/marketplace'
    | '/app/recommendations'
    | '/app/risk'
    | '/app/voice'
    | '/app/workflows'
    | '/app/'
    | '/app/settings/branding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/bi'
    | '/app/command'
    | '/app/copilot'
    | '/app/crm'
    | '/app/dealrooms'
    | '/app/documents'
    | '/app/feed'
    | '/app/graph'
    | '/app/kie'
    | '/app/leads'
    | '/app/market'
    | '/app/marketplace'
    | '/app/recommendations'
    | '/app/risk'
    | '/app/voice'
    | '/app/workflows'
    | '/app'
    | '/app/settings/branding'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/bi'
    | '/app/command'
    | '/app/copilot'
    | '/app/crm'
    | '/app/dealrooms'
    | '/app/documents'
    | '/app/feed'
    | '/app/graph'
    | '/app/kie'
    | '/app/leads'
    | '/app/market'
    | '/app/marketplace'
    | '/app/recommendations'
    | '/app/risk'
    | '/app/voice'
    | '/app/workflows'
    | '/app/'
    | '/app/settings/branding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workflows': {
      id: '/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AppWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/voice': {
      id: '/app/voice'
      path: '/voice'
      fullPath: '/app/voice'
      preLoaderRoute: typeof AppVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/risk': {
      id: '/app/risk'
      path: '/risk'
      fullPath: '/app/risk'
      preLoaderRoute: typeof AppRiskRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recommendations': {
      id: '/app/recommendations'
      path: '/recommendations'
      fullPath: '/app/recommendations'
      preLoaderRoute: typeof AppRecommendationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketplace': {
      id: '/app/marketplace'
      path: '/marketplace'
      fullPath: '/app/marketplace'
      preLoaderRoute: typeof AppMarketplaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/market': {
      id: '/app/market'
      path: '/market'
      fullPath: '/app/market'
      preLoaderRoute: typeof AppMarketRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads': {
      id: '/app/leads'
      path: '/leads'
      fullPath: '/app/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/kie': {
      id: '/app/kie'
      path: '/kie'
      fullPath: '/app/kie'
      preLoaderRoute: typeof AppKieRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/graph': {
      id: '/app/graph'
      path: '/graph'
      fullPath: '/app/graph'
      preLoaderRoute: typeof AppGraphRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feed': {
      id: '/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AppFeedRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dealrooms': {
      id: '/app/dealrooms'
      path: '/dealrooms'
      fullPath: '/app/dealrooms'
      preLoaderRoute: typeof AppDealroomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/copilot': {
      id: '/app/copilot'
      path: '/copilot'
      fullPath: '/app/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/command': {
      id: '/app/command'
      path: '/command'
      fullPath: '/app/command'
      preLoaderRoute: typeof AppCommandRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bi': {
      id: '/app/bi'
      path: '/bi'
      fullPath: '/app/bi'
      preLoaderRoute: typeof AppBiRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings/branding': {
      id: '/app/settings/branding'
      path: '/settings/branding'
      fullPath: '/app/settings/branding'
      preLoaderRoute: typeof AppSettingsBrandingRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBiRoute: typeof AppBiRoute
  AppCommandRoute: typeof AppCommandRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDealroomsRoute: typeof AppDealroomsRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppFeedRoute: typeof AppFeedRoute
  AppGraphRoute: typeof AppGraphRoute
  AppKieRoute: typeof AppKieRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppMarketRoute: typeof AppMarketRoute
  AppMarketplaceRoute: typeof AppMarketplaceRoute
  AppRecommendationsRoute: typeof AppRecommendationsRoute
  AppRiskRoute: typeof AppRiskRoute
  AppVoiceRoute: typeof AppVoiceRoute
  AppWorkflowsRoute: typeof AppWorkflowsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSettingsBrandingRoute: typeof AppSettingsBrandingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBiRoute: AppBiRoute,
  AppCommandRoute: AppCommandRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppCrmRoute: AppCrmRoute,
  AppDealroomsRoute: AppDealroomsRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppFeedRoute: AppFeedRoute,
  AppGraphRoute: AppGraphRoute,
  AppKieRoute: AppKieRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppMarketRoute: AppMarketRoute,
  AppMarketplaceRoute: AppMarketplaceRoute,
  AppRecommendationsRoute: AppRecommendationsRoute,
  AppRiskRoute: AppRiskRoute,
  AppVoiceRoute: AppVoiceRoute,
  AppWorkflowsRoute: AppWorkflowsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSettingsBrandingRoute: AppSettingsBrandingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
