// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { supabaseAdmin } from './client.server'

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL || process.env.VITE_SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || process.env.VITE_SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Please configure Supabase environment variables.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();
    let token: string | null = null;

    if (request?.headers) {
      const authHeader = request.headers.get('authorization');
      if (authHeader && authHeader.startsWith('Bearer ')) {
        token = authHeader.replace('Bearer ', '').trim();
      }

      if (!token) {
        const cookieHeader = request.headers.get('cookie') || '';
        const projectRef = process.env.SUPABASE_PROJECT_ID || process.env.VITE_SUPABASE_PROJECT_ID;
        const projectMatch = projectRef ? cookieHeader.match(new RegExp(`sb-${projectRef}-auth-token=([^;]+)`)) : null;
        const genericMatch = cookieHeader.match(/sb-[a-z0-9_-]+-auth-token=([^;]+)/);
        const match = projectMatch || genericMatch ||
                      cookieHeader.match(/sb-access-token=([^;]+)/) ||
                      cookieHeader.match(/supabase-auth-token=([^;]+)/);
        if (match) {
          try {
            const decoded = decodeURIComponent(match[1]);
            if (decoded.startsWith('[') || decoded.startsWith('{')) {
              const parsed = JSON.parse(decoded);
              token = Array.isArray(parsed) ? parsed[0] : (parsed.access_token || parsed.token || null);
            } else {
              token = decoded;
            }
          } catch {
            token = match[1];
          }
        }
      }
    }

    let supabase = supabaseAdmin;
    let user: any = null;

    if (token) {
      supabase = createClient<Database>(
        SUPABASE_URL!,
        SUPABASE_PUBLISHABLE_KEY!,
        {
          global: {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        }
      );

      try {
        const userPromise = supabase.auth.getUser(token);
        const timeoutPromise = new Promise((_, reject) =>
          setTimeout(() => reject(new Error('Auth timeout')), 2500)
        );
        const { data, error } = (await Promise.race([userPromise, timeoutPromise])) as any;
        if (!error && data?.user) {
          user = data.user;
        }
      } catch (e) {
        console.warn('[auth-middleware] getUser failed or timed out:', e);
      }

    }

    // Never trust an unverified JWT or create a fallback administrator.
    if (!user || !user.id || !token) {
      console.warn("[auth-middleware] Rejected unverified or missing session");
      throw new Response("Unauthorized", { status: 401 });
    }

    return next({
      context: {
        supabase: supabase || supabaseAdmin,
        userId: user.id,
        claims: user,
        roles: ['admin', 'manager', 'agent', 'viewer', 'builder', 'developer'],
      },
    });
  },
);